// Cast brand asset generator — the single source of truth for the brand mark.
// Run with: bun tools/brand/generate.js (from the repo root)
//
// Emits, from the locked seeded recipe (see docs/superpowers/specs/2026-06-12-*.md):
//   android/.../drawable/ic_launcher_foreground.xml   adaptive icon foreground
//   android/.../drawable/ic_launcher_monochrome.xml   themed-icon layer
//   webapp/static/favicon.svg                          favicon with glow
//
// Never hand-edit the generated files; change the recipe here and rerun.

const TWO_PI = Math.PI * 2;
const STEPS = 240;

const BG = '#0D1530';
const MAIN_COLOR = '#FF8A4D';
const RING_COLORS = ['#FFE14D', '#FF5FA8', '#57FFCB', '#5BC8FF', '#C77DFF'];
const RING_WIDTHS = [1.4, 2.0, 2.6, 1.7, 3.0];
const MAIN_WIDTH = 7;
const HALO_WIDTH = 10.5;
const MAIN_SEED = 20260612;
const ARRANGEMENT_SEED = 980311; // "arrangement 4" from the brainstorm session

function mulberry32(seed) {
  return function () {
    seed |= 0; seed = (seed + 0x6D2B79F5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// Closed polyline approximating a circle whose radius is modulated by summed
// sinusoids: r(θ) = R·(1 + Σ aᵢ·sin(fᵢθ + pᵢ)), rotated by rot, in caller units.
function wobblePath(R, harmonics, rot, cx, cy, scale) {
  const pts = [];
  for (let i = 0; i < STEPS; i++) {
    const th = (i / STEPS) * TWO_PI;
    let r = R;
    for (const { f, a, p } of harmonics) r += R * a * Math.sin(f * th + p);
    const phi = th + rot;
    pts.push((cx + r * scale * Math.cos(phi)).toFixed(1) + ',' + (cy + r * scale * Math.sin(phi)).toFixed(1));
  }
  return 'M' + pts.join('L') + 'Z';
}

// PRNG draw order is part of the recipe — do not reorder.
function mainPath(cx, cy, scale) {
  const rng = mulberry32(MAIN_SEED);
  return wobblePath(60, [
    { f: 9, a: 0.022, p: rng() * TWO_PI },
    { f: 17, a: 0.014, p: rng() * TWO_PI },
    { f: 31, a: 0.008, p: rng() * TWO_PI },
  ], 0, cx, cy, scale);
}

function thinRingPaths(cx, cy, scale) {
  const rng = mulberry32(ARRANGEMENT_SEED);
  const paths = [];
  for (let i = 0; i < 5; i++) {
    paths.push(wobblePath(60, [
      { f: 2 + (i % 3), a: 0.21 + rng() * 0.05, p: rng() * TWO_PI },
      { f: 5 + i, a: 0.21 * 0.45 + rng() * 0.03, p: rng() * TWO_PI },
      { f: 17 + i * 2, a: 0.007, p: rng() * TWO_PI },
    ], rng() * TWO_PI, cx, cy, scale));
  }
  return paths;
}

// ---- Android adaptive icon foreground (108dp viewport, flat: no glow) --------------------
// Scale 0.41 dp/unit puts the main ring at ~24.6dp radius (inside the 33dp safe zone
// including its halo) while the thin rings reach ~34dp, bleeding toward the mask edge.
const ICON_SCALE = 0.41;

function vectorPath(d, stroke, width) {
  return `    <path
        android:fillColor="#00000000"
        android:strokeColor="${stroke}"
        android:strokeWidth="${width.toFixed(2)}"
        android:pathData="${d}" />`;
}

function foregroundXml() {
  const thins = thinRingPaths(54, 54, ICON_SCALE);
  const main = mainPath(54, 54, ICON_SCALE);
  const paths = [
    ...thins.map((d, i) => vectorPath(d, RING_COLORS[i], RING_WIDTHS[i] * ICON_SCALE)),
    vectorPath(main, BG, HALO_WIDTH * ICON_SCALE),
    vectorPath(main, MAIN_COLOR, MAIN_WIDTH * ICON_SCALE),
  ];
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/brand/generate.js - do not hand-edit. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
${paths.join('\n')}
</vector>
`;
}

// ---- Themed-icon monochrome layer: main ring + mint and violet ring geometries -----------
function monochromeXml() {
  const thins = thinRingPaths(54, 54, ICON_SCALE);
  const main = mainPath(54, 54, ICON_SCALE);
  const paths = [
    vectorPath(thins[2], '#FFFFFF', RING_WIDTHS[2] * ICON_SCALE),
    vectorPath(thins[4], '#FFFFFF', RING_WIDTHS[4] * ICON_SCALE),
    vectorPath(main, '#FFFFFF', MAIN_WIDTH * ICON_SCALE),
  ];
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/brand/generate.js - do not hand-edit. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
${paths.join('\n')}
</vector>
`;
}

// ---- Webapp favicon (full SVG, glows included) --------------------------------------------
function faviconSvg() {
  const thins = thinRingPaths(100, 100, 1);
  const main = mainPath(100, 100, 1);
  const rings = thins.map((d, i) =>
    `  <path d="${d}" fill="none" stroke="${RING_COLORS[i]}" stroke-width="${RING_WIDTHS[i]}" filter="url(#ring-glow)"/>`
  ).join('\n');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200">
  <!-- Generated by tools/brand/generate.js - do not hand-edit. -->
  <filter id="ring-glow" x="-25%" y="-25%" width="150%" height="150%">
    <feGaussianBlur stdDeviation="0.9" result="b"/>
    <feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge>
  </filter>
  <filter id="main-glow" x="-30%" y="-30%" width="160%" height="160%">
    <feGaussianBlur stdDeviation="1.6" result="b"/>
    <feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge>
  </filter>
  <rect width="200" height="200" rx="40" fill="${BG}"/>
${rings}
  <path d="${main}" fill="none" stroke="${BG}" stroke-width="${HALO_WIDTH}"/>
  <path d="${main}" fill="none" stroke="${MAIN_COLOR}" stroke-width="${MAIN_WIDTH}" filter="url(#main-glow)"/>
</svg>
`;
}

const root = new URL('../..', import.meta.url).pathname;
const out = [
  ['android/app/src/main/res/drawable/ic_launcher_foreground.xml', foregroundXml()],
  ['android/app/src/main/res/drawable/ic_launcher_monochrome.xml', monochromeXml()],
  ['webapp/static/favicon.svg', faviconSvg()],
];
for (const [rel, content] of out) {
  await Bun.write(root + rel, content);
  console.log('wrote', rel);
}
